name: Make My APK

on:
  workflow_dispatch: # 允许手动点击按钮运行

jobs:
  build-me-an-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 下载代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 安装 Java 环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. 安装 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. 下载依赖包
      - name: Get Packages
        run: flutter pub get

      # 5. 开始编译 (使用Debug模式，跳过签名验证)
      - name: Build Debug APK
        run: flutter build apk --debug

      # 6. 上传编译好的文件
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-app
          path: build/app/outputs/flutter-apk/app-debug.apk
